### ISSUE TITLE
1.4.2 crashes with "syntax error near unexpected token `then'"

### ISSUE THREAD

**Issue by andrewaarestad** [sawadashota/envsubst-orb#10]
We are using `envsubst@volatile` so we pulled in the 1.4.2 release.  It's breaking our CI with the following error:

```
/bin/bash: -c: line 6: syntax error near unexpected token `then'

Exited with code exit status 2
```

We locked envsubst orb version to 1.1.0 to fix.

Running in Circle CI on linux, x86_64

**Comment by DinoLeung** [comment]
#9 is fixing this issue, waiting to merge in

**Comment by sawadashota** [comment]
merged
